# Generated by Django 6.0.1 on 2026-01-30 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_attendance_ratings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='ratings',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time_completed',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_created',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
