# Generated by Django 6.0.1 on 2026-01-31 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='ratings',
            new_name='rating',
        ),
    ]
